logging:
  level:
    com: DEBUG
    org: DEBUG
    io: DEBUG
  file:
    name: ./logs/bootiful-APIs.log

server:
  port: 8443

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf624vay34448bg30.mysql.rds.aliyuncs.com:3306/mars-rds-instance1?characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: mars_rw_acc1
    password: Hsbc@123!
    hikari:
      poolName: MARS-Repository-Connection-Pool
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 180000 
